/**********************************************************************************
***********************************************************************************
**														  						 **		
**	FILENAME	:	ComStack_Cfg.h                  						     **
**	                                                      						 **
**	VERSION		: 	1.0.0                                 						 **
**                                                        						 **
**	DATE		:	2021-4-2                             						 **
**                                                        						 **
**	PLATFORM	:	TIVA C      		                  						 **
**																				 **
**  VARIANT  	: 	NA                                                           **
**                                                        						 **
**	AUTHOR		:  	MohamedSayed                          						 **
**                                                        						 **
**	VENDOR		: 	NA				                     						 **
**                                                        						 **
**	                                                      						 **
**	DESCRIPTION : Commmunication stack Configuration Header File.     			 **
**                                                                               **
**	SPECIFICATION(S): AUTOSAR Release 4.3.1 									 **
**                                                       						 **
**	MAY BE CHANGED BY USER : No                          						 **
**                                                       					     **
***********************************************************************************/
#ifndef COMSTACK_CFG_H 
#define COMSTACK_CFG_H

/*
	[SWS_Comtype_00029] ComStack_Cfg.h shall be generated by the generator to generate the
	type definition of the PduIdType and PduLengthType from the EcuC Virtual Layer based 
	on the configuration e.g.typedef uint8 PduIdType if number of PDUs are less than 256.
*/


#endif /* COMSTACK_CFG_H */

